name: Update WakaTime stats

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_TITLE: false
          TIME_RANGE: all_time
          LANG_COUNT: 3
          STOP_AT_OTHER: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          CODE_LANG: txt
          BLOCKS: ▰▰▰▱▱
